version: '3.8'

services:
  cache:
    image: redis/redis-stack:latest
    container_name: todo-cache
    restart: always
    ports:
      - 6379:6379
      - 8001:8001
    environment:
      - REDIS_PORT=6379
  todo-api:
    image: todo-api:v5
    container_name: todo-api-5
    restart: always
    environment:
      - REDIS_URL=cache:6379
    ports:
      - 1080:1080
    depends_on:
      - cache

