version: '3.8'
services:
  cache:
    image: redis/redis-stack:latest
    container_name: pub-cache
    restart: on-failure
    ports:
      - '6379:6379'
      - '8001:8001'
    volumes:
      - ./dbdata:/data
    environment:
      - REDIS_ARGS=--appendonly yes
    networks:
      - backend

  cache-init:
    image: redis/redis-stack:latest
    container_name: pub-cache-init
    volumes:
      - ./dbdata:/data
    environment:
      - REDIS_ARGS=--appendonly yes
    command: /data/load-redis.sh cache
    networks:
      - frontend
      - backend
    depends_on:
      cache:
        condition: service_started
    
    
  pub-api:
    image: architectingsoftware/cnse-pub-api:v1
    container_name: pub-api-1
    restart: always
    ports:
      - '2080:2080'
    depends_on:
      cache-init:
        condition: service_completed_successfully
    environment:
      - PUBAPI_CACHE_URL=cache:6379
    networks:
      - frontend
      - backend

  publist-api:
    image: architectingsoftware/cnse-publist-api:v1
    container_name: pub-list-1
    restart: always
    ports:
      - '3080:3080'
    depends_on:
      cache-init:
        condition: service_completed_successfully
    environment:
      - RLAPI_CACHE_URL=cache:6379
      - RLAPI_PUB_API_URL=http://pub-api:2080 
    networks:
      - frontend
      - backend


networks:
  frontend:
    internal: false
  backend:
    internal: true