version: '3.8'
services:
  cache:
    image: redis/redis-stack:latest
    container_name: todo-cache
    restart: on-failure
    ports:
      - '6379:6379'
      - '8001:8001'
    volumes:
      - ../cache-data:/data
    environment:
      - REDIS_ARGS=--appendonly yes
    networks:
      - backend
      - frontend
  todo-api:
    image: todo-api-basic:v3
    container_name: todo-api-1
    restart: always
    ports:
      - '1080:1080'
    depends_on:
      - cache
    environment:
      - REDIS_URL=cache:6379
    networks:
      - frontend
      - backend
networks:
  frontend:
    internal: false
  backend:
    internal: true