apiVersion: v1
kind: PersistentVolume
metadata:
  name: cache-pv
  namespace: cnse
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 256M
  hostPath:
    path: /tmp/data/
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cache-pvc
  namespace: cnse
spec:
  volumeName: cache-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256M